### ISSUE TITLE
add support for `rolloutstatus` for each resources in maya.

### ISSUE THREAD

**Issue by shovanmaity** [openebs/maya#1148]
### What is rolloutstatus
RolloutStatus represents if new changes when applied against a resource are rolled out successfully or not. 

NOTE: kubectl has rolloutstatus for Deployment , StatefulSet and DaemonSet.

### Why is this required?
This is very helpful when used for upgrade(s).

### RunTask without `rolloutstatus` for `kind: Deployment`
```yaml
apiVersion: openebs.io/v1alpha1
kind: RunTask
metadata:
  name: task-waitforpatchstatus
  namespace: default
spec:
  meta: |
    {{- $name := .TaskResult.deploymentname | default "" -}}
    id: waitforpatchstatus
    runNamespace: openebs
    apiVersion: extensions/v1beta1
    kind: Deployment
    action: get
    objectName: {{ $name }}
    retry: "20,120s"
  post: |
    {{- $replicas := .TaskResult.replicacount | default "" -}}
    {{- $updatedReplicas := .TaskResult.updatedReplicacount | default "" -}}
    {{- $readyReplicas := .TaskResult.readyReplicacount | default "" -}}
    {{- $availableReplicas := .TaskResult.availableReplicacount | default "" -}}
    {{- "" | saveAs "verifyErr" .TaskResult | noop -}}
    {{- if eq $replicas "" }}
    {{- "replica count not  present" | saveAs "waitforpatchstatus.verifyErr" .TaskResult | noop -}}
    {{- end }}
    {{- if eq $updatedReplicas "" }}
    {{- "updated replica count not  present" | saveAs "waitforpatchstatus.verifyErr" .TaskResult | noop -}}
    {{- end }}
    {{- if eq $readyReplicas "" }}
    {{- "ready replica count not  present" | saveAs "waitforpatchstatus.verifyErr" .TaskResult | noop -}}
    {{- end }}
    {{- if eq $availableReplicas "" }}
    {{- "available replica count not  present" | saveAs "waitforpatchstatus.verifyErr" .TaskResult | noop -}}
    {{- end }}
    {{- if ne $replicas $updatedReplicas }}
    {{- "replica count is not equal with updated replica count" | saveAs "waitforpatchstatus.verifyErr" .TaskResult | noop -}}
    {{- end }}
    {{- if ne $replicas $readyReplicas }}
    {{- "replica count is not equal with ready replica count" | saveAs "waitforpatchstatus.verifyErr" .TaskResult | noop -}}
    {{- end }}
    {{- if ne $replicas $availableReplicas }}
    {{- "replica count is not equal with available replica count" | saveAs "waitforpatchstatus.verifyErr" .TaskResult | noop -}}
    {{- end }}
    {{- jsonpath .JsonResult "{.status.replicas}" | trim | saveAs "replicacount" .TaskResult | default "" noop -}}
    {{- jsonpath .JsonResult "{.status.updatedReplicas}" | trim | saveAs "updatedReplicacount" .TaskResult | default "" noop -}}
    {{- jsonpath .JsonResult "{.status.readyReplicas}" | trim | saveAs "readyReplicacount" .TaskResult | default "" noop -}}
    {{- jsonpath .JsonResult "{.status.availableReplicas}" | trim | saveAs "availableReplicacount" .TaskResult | default "" noop -}}
```

### RunTask with `action: rolloutstatus` for `kind: Deployment`
```yaml
apiVersion: openebs.io/v1alpha1
kind: RunTask
metadata:
  name: upgrade-cstor-pool-080-081-pool-deployment-status
  namespace: default
spec:
  meta: |
    id: poolDeploymentImageStatus
    apiVersion: extensions/v1beta1
    kind: Deployment
    action: rolloutstatus
    objectName: {{ .UpgradeItem.name }}
    runNamespace: {{ .UpgradeItem.namespace }}
    disable: false
  post: |
    {{- jsonpath .JsonResult "{.isRolledout}" | trim | saveAs "poolDeploymentStatus.isRolledOut" .TaskResult | noop -}}
    {{- jsonpath .JsonResult "{.message}" | trim | saveAs "poolDeploymentStatus.rolloutStatus" .TaskResult | noop -}}
    {{- if eq .TaskResult.poolDeploymentStatus.isRolledOut  "true" }}
    {{- else }}
    {{- "waiting for deployment rollout" | saveAs "poolDeploymentStatus.verifyErr" .TaskResult | noop -}}
    {{- end }}
```

For Upgrade our unit of upgrade is CStorPool and CStorVolumes before upgrading we must check status of pool and volume and it can be done if we add rolloutstatus action for CStorPool and CStorVolume.

**Comment by AmitKumarDas** [comment]
Can we have below that eliminates `post` as well?
e.g.

```yaml
apiVersion: openebs.io/v1alpha1
kind: RunTask
metadata:
  name: upgrade-cstor-pool-080-081-pool-deployment-status
  namespace: default
spec:
  meta: |
    id: poolDeployRollout
    apiVersion: extensions/v1beta1
    kind: Deployment
    action: rolloutstatus
    objectName: {{ .UpgradeItem.name }}
    runNamespace: {{ .UpgradeItem.namespace }}
    retry: 10, 3s
post: |
```

- Above should set below map against task id i.e. poolDeployRollout
  - isRolledOut: true/false
  - message: "blah blah blah"
- One should be able to extract rolloutstatus results as follows:
  - `.TaskResult.poolDeployRollout.isRolledOut` &
  - `.TaskResult.poolDeployRollout.message`
- Above should retry if `isRolledout` is false based on `retry`
- VerifyError should be set internally if `isRolledout` is false
